apiVersion: v1

kind: PersistentVolumeClaim

metadata:
  name: mywebpvc

spec:
  storageClassName: manual
  
  accessModes:
    - ReadWriteOnce
  
  resources:
    requests:
      storage: 1Gi
